# Generated by Django 4.2.7 on 2025-12-18 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_bill_bill_number_alter_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
    ]
